2019-04-08 22:34:55,425 - root - ERROR - put请求出错，出错原因:HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /todos/todo1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239D2896F98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-04-08 22:34:55,425 - root - INFO - 请求传入数据：url:http://127.0.0.1:5000/todos/todo1,key:10.0,参数:{"task":"put success"},请求方式：PUT
2019-04-08 22:34:55,425 - root - INFO - 测试用例执行完毕
2019-04-08 22:34:55,426 - root - INFO - ----------------------------------
2019-04-08 22:34:55,427 - root - INFO - 测试用例开始执行
2019-04-08 22:34:55,428 - root - INFO - 获取用例数据:{'url': 'http://127.0.0.1:5000/todos/todo2', 'listname': 'put请求返回resultcode和task正确', 'key': 11.0, 'coneent': '{"task":"update success"}', 'param_place': 'database', 'fangshi': 'PUT', 'expect1': 'code=201', 'expect2': 'task=update success'}
2019-04-08 22:34:55,431 - root - INFO - 当前接口涉及数据库：orderdb
2019-04-08 22:34:55,595 - root - INFO - 成功登录数据库：orderdb，版本为：8.0.11，执行SQL：select content from blog_blog where id = '7'
2019-04-08 22:34:55,627 - root - INFO - 查询结果：{"task":"update success"}
2019-04-08 22:34:55,628 - root - INFO - 数据格式为：{"task":"update success"}
