2019-04-08 22:34:50,381 - root - ERROR - put请求出错，出错原因:HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /todos/todo2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239D28B76D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-04-08 22:34:50,382 - root - INFO - 请求传入数据：url:http://127.0.0.1:5000/todos/todo2,key:5.0,参数:{"task":"update success"},请求方式：PUT
2019-04-08 22:34:50,382 - root - INFO - 测试用例执行完毕
2019-04-08 22:34:50,383 - root - INFO - ----------------------------------
2019-04-08 22:34:50,384 - root - INFO - 测试用例开始执行
2019-04-08 22:34:50,385 - root - INFO - 获取用例数据:{'url': 'http://127.0.0.1:5000/todos/todo1', 'listname': 'delete请求成功删除数据', 'key': 6.0, 'coneent': 'not argument', 'param_place': '', 'fangshi': 'DELETE', 'expect1': 'code=204', 'expect2': 'param=null'}
